/* AP Webcraft — 25 academic projects per technology */
var TECH_PROJECTS = {
  "Web Development": [
    "Personal Portfolio Website",
    "College Website with CMS",
    "Restaurant Business Website",
    "School Management Website",
    "Real Estate Listing Portal",
    "Hospital Information Website",
    "Event Registration Website",
    "NGO Donation Website",
    "Tourism Travel Booking Site",
    "Photography Portfolio Gallery",
    "Gym Fitness Center Website",
    "Online Resume Builder Website",
    "News Magazine Portal",
    "Wedding Planner Website",
    "Job Consultancy Website",
    "Law Firm Corporate Website",
    "Dental Clinic Appointment Website",
    "Fashion Boutique E-Commerce Site",
    "Interior Design Showcase Website",
    "Coaching Institute Website",
    "Pet Care Services Website",
    "Agriculture Farmer Portal",
    "Construction Company Website",
    "Music Band Artist Website",
    "Salon Spa Booking Website"
  ],
  "Java": [
    "Online Examination System",
    "Library Management System",
    "Student Attendance Management System",
    "Hotel Booking Management System",
    "Banking Management System",
    "Employee Payroll Management System",
    "Inventory Management System",
    "Online Voting System",
    "Railway Reservation System",
    "College Admission Management System",
    "Vehicle Parking Management System",
    "ATM Simulation System",
    "Courier Tracking System",
    "Restaurant Billing System",
    "Online Quiz Application",
    "Blood Bank Management System",
    "Crime Record Management System",
    "Hostel Management System",
    "Insurance Policy Management System",
    "Online Auction System",
    "Complaint Management System",
    "Electricity Bill Payment System",
    "Movie Ticket Booking System",
    "Alumni Association Portal",
    "Campus Recruitment Portal"
  ],
  "Python": [
    "Face Recognition Attendance System",
    "Fake News Detection using NLP",
    "Crop Yield Prediction using ML",
    "Sentiment Analysis of Social Media",
    "Weather Forecasting using ML",
    "House Price Prediction Model",
    "Heart Disease Prediction System",
    "Spam Email Classification",
    "Handwritten Digit Recognition",
    "Stock Price Prediction System",
    "Customer Churn Prediction",
    "Traffic Sign Recognition",
    "Emotion Detection from Text",
    "Loan Default Prediction",
    "Music Genre Classification",
    "Object Detection using YOLO",
    "Air Quality Index Prediction",
    "Plant Disease Detection",
    "Resume Parser and Analyzer",
    "Chatbot using NLTK",
    "Iris Flower Classification",
    "Titanic Survival Prediction",
    "Speech Emotion Recognition",
    "License Plate Recognition",
    "Credit Card Fraud Detection"
  ],
  "PHP": [
    "Hospital Management System",
    "College Placement Portal",
    "Online Shopping Cart System",
    "Student Result Management System",
    "Online Food Ordering System",
    "Car Rental Management System",
    "Online Bus Ticket Booking",
    "Clinic Appointment Booking System",
    "Online Jewellery Store",
    "School Fee Management System",
    "Online Grocery Store",
    "Travel Agency Booking Portal",
    "Online Book Store",
    "Employee Leave Management System",
    "Online Furniture Store",
    "Taxi Booking Management System",
    "Online Medicine Store",
    "Beauty Salon Booking System",
    "Online Electronics Store",
    "Car Service Center Portal",
    "Online Bakery Shop",
    "Hostel Room Booking System",
    "Online Stationery Store",
    "Wedding Hall Booking System",
    "Online Sports Equipment Store"
  ],
  "JavaScript": [
    "To-Do List Application",
    "Weather Forecast App",
    "Calculator Web Application",
    "Quiz Game Application",
    "Password Generator Tool",
    "Notes Taking Application",
    "Countdown Timer Application",
    "BMI Calculator Application",
    "Currency Converter Application",
    "Random Quote Generator",
    "Memory Card Game",
    "Stopwatch Application",
    "Tip Calculator Application",
    "Color Palette Generator",
    "Typing Speed Test Application",
    "Expense Tracker Application",
    "Pomodoro Timer Application",
    "Digital Clock Application",
    "Age Calculator Application",
    "Rock Paper Scissors Game",
    "Tic Tac Toe Game",
    "Snake Game Application",
    "Image Slider Gallery",
    "Form Validation System",
    "Interactive Resume Builder"
  ],
  "React": [
    "E-Commerce Website using React",
    "Social Media Dashboard",
    "Task Management Kanban Board",
    "Movie Database Search App",
    "Cryptocurrency Price Tracker",
    "Blog Platform with React",
    "Recipe Finder Application",
    "Online Learning Platform UI",
    "Job Portal Frontend",
    "Real-Time Chat Interface",
    "Music Player Application",
    "Travel Destination Explorer",
    "Fitness Workout Tracker",
    "Restaurant Menu Ordering App",
    "Portfolio Website with React",
    "Weather Dashboard Application",
    "Event Ticket Booking App",
    "Online Quiz Platform",
    "Product Review Platform",
    "News Aggregator Application",
    "Shopping Wishlist Manager",
    "Hospital Patient Portal",
    "Stock Market Dashboard",
    "Online Exam Interface",
    "Food Delivery Tracking App"
  ],
  "Node.js": [
    "Real-Time Chat Application",
    "REST API for Blog Platform",
    "Online Polling System",
    "URL Shortener Service",
    "File Upload and Sharing API",
    "E-Commerce Backend API",
    "Authentication System with JWT",
    "Real-Time Notification Service",
    "Video Streaming Backend",
    "Job Portal REST API",
    "Social Media Backend API",
    "Online Booking System API",
    "Inventory Management API",
    "Payment Gateway Integration API",
    "Email Newsletter Service",
    "Multiplayer Game Server",
    "Food Delivery Order API",
    "Hospital Appointment API",
    "Student Management REST API",
    "Chatbot Backend Service",
    "Analytics Dashboard API",
    "Content Management System API",
    "Event Registration API",
    "Online Voting Backend",
    "Collaborative Document Editor API"
  ],
  "Spring Boot": [
    "Employee Payroll Management System",
    "Student Result Management System",
    "Online Banking Portal",
    "Hospital Management System",
    "E-Commerce Backend with Spring Boot",
    "Library Management System",
    "College Admission Portal",
    "Inventory Management System",
    "Online Examination System",
    "Hotel Reservation System",
    "CRM Customer Management System",
    "Insurance Claim Management System",
    "Vehicle Rental Management System",
    "Online Ticket Booking System",
    "Employee Attendance System",
    "University Course Registration System",
    "Pharmacy Management System",
    "Warehouse Management System",
    "Online Food Ordering Backend",
    "Complaint Ticketing System",
    "Alumni Management Portal",
    "Document Management System",
    "Recruitment Management Portal",
    "Billing and Invoice System",
    "AI Healthcare Management Portal"
  ],
  "Laravel": [
    "Blood Bank Management System",
    "Job Search Portal for Freshers",
    "Online Learning Management System",
    "Multi-Vendor E-Commerce Platform",
    "Hospital Patient Management System",
    "Real Estate Property Listing Portal",
    "Event Management System",
    "Restaurant Order Management System",
    "School Management System",
    "Blog CMS with Laravel",
    "Courier Delivery Management System",
    "Hotel Room Booking System",
    "Online Examination Portal",
    "Inventory and Sales Management",
    "Charity Donation Platform",
    "Travel Booking Management System",
    "Clinic Appointment Scheduler",
    "Freelancer Marketplace Platform",
    "Online Grocery Delivery System",
    "Car Rental Booking Platform",
    "Membership Subscription Portal",
    "Help Desk Ticketing System",
    "Online Voting Platform",
    "Alumni Networking Portal",
    "Digital Library Management System"
  ],
  "CodeIgniter": [
    "Restaurant Table Booking System",
    "Student Information System",
    "Online Quiz Management System",
    "Clinic Management System",
    "School Fee Collection Portal",
    "Hostel Management System",
    "Online Attendance System",
    "Inventory Tracking System",
    "Employee Management Portal",
    "Online Complaint Registration",
    "Blood Donation Camp Portal",
    "College Event Registration System",
    "Online Leave Application System",
    "Vehicle Service Center Portal",
    "Online Admission Form System",
    "Library Book Issue System",
    "Online Result Publication Portal",
    "Coaching Class Management System",
    "Online Feedback Collection System",
    "Sports Event Registration Portal",
    "Online Certificate Generation System",
    "Timetable Management System",
    "Online Alumni Registration Portal",
    "Student Assignment Portal",
    "Online Notice Board System"
  ],
  "Django": [
    "Real Estate Listing Website",
    "Online Learning Platform",
    "Blog and Article Publishing Site",
    "E-Commerce Store with Django",
    "Hospital Appointment Booking System",
    "Social Networking Platform",
    "Online Voting System with OTP",
    "Restaurant Food Ordering Platform",
    "Job Portal with Django",
    "Event Ticket Booking System",
    "News Portal with Admin Panel",
    "Online Examination Platform",
    "Travel Agency Booking System",
    "Music Streaming Platform",
    "Online Library Management System",
    "Crowdfunding Donation Platform",
    "Online Course Enrollment System",
    "Fitness Gym Membership Portal",
    "Online Pharmacy Store",
    "Car Rental Booking Platform",
    "Online Polling and Survey System",
    "Digital Portfolio Platform",
    "Online Complaint Management System",
    "University Alumni Portal",
    "Online Internship Portal"
  ],
  "Flask": [
    "Personal Finance Tracker using Flask",
    "URL Shortener Web Application",
    "Blog Platform with Flask",
    "Weather API Dashboard",
    "Task Manager Web Application",
    "Online Quiz Application",
    "Expense Splitting Application",
    "Contact Management System",
    "File Sharing Web Application",
    "Recipe Sharing Platform",
    "Movie Review Platform",
    "Online Polling Application",
    "Student Grade Calculator",
    "Book Review Platform",
    "Event RSVP Management System",
    "Simple E-Commerce Store",
    "Password Manager Application",
    "Habit Tracker Application",
    "Online Resume Builder",
    "Photo Gallery Web Application",
    "Note Taking Web Application",
    "Inventory Tracker Application",
    "Online Feedback Form System",
    "Appointment Scheduling System",
    "Portfolio Showcase Website"
  ],
  "FastAPI": [
    "REST API for Inventory Management",
    "User Authentication Microservice",
    "Real-Time Chat API Backend",
    "E-Commerce Product Catalog API",
    "Blog Post Management API",
    "Hospital Patient Records API",
    "Online Booking System API",
    "File Upload and Storage API",
    "Notification Service API",
    "Payment Processing API",
    "Search and Filter API Service",
    "Analytics Data API",
    "Task Queue Management API",
    "Email Service Microservice",
    "Social Media Feed API",
    "Weather Data API Service",
    "Order Tracking API",
    "Review and Rating API",
    "Subscription Billing API",
    "Content Delivery API",
    "Image Processing API Service",
    "Machine Learning Prediction API",
    "Document Parser API Service",
    "Location Tracking API",
    "Webhook Event Handler API"
  ],
  "Android": [
    "Smart Attendance Tracker App",
    "Expense Manager Mobile App",
    "Blood Donation Finder App",
    "College Campus Navigation App",
    "Online Grocery Shopping App",
    "Fitness and Workout Tracker",
    "Bus Tracking Mobile Application",
    "Restaurant Food Ordering App",
    "Medicine Reminder Mobile App",
    "Student Notes Sharing App",
    "Parking Slot Finder App",
    "Local Job Search Mobile App",
    "Weather Alert Mobile App",
    "QR Code Attendance App",
    "Event Ticket Booking App",
    "Library Book Search App",
    "Cab Booking Mobile Application",
    "Recipe Finder Mobile App",
    "Daily Task Reminder App",
    "College Timetable Viewer App",
    "Online Quiz Mobile App",
    "Hostel Complaint Registration App",
    "Campus Lost and Found App",
    "Student Portfolio Mobile App",
    "Emergency SOS Safety App"
  ],
  "Flutter": [
    "Android Based Attendance Tracker",
    "Farmer Marketplace Mobile App",
    "EmergeCare Blood Bank Management App",
    "AI Multi-Functional Assistant App",
    "Budget Planner Mobile Application",
    "Language Learning Mobile App",
    "Food Delivery Mobile Application",
    "Fitness Tracker Cross-Platform App",
    "Online Learning Mobile Platform",
    "Travel Booking Mobile App",
    "Grocery Shopping Mobile App",
    "Hospital Appointment Booking App",
    "Real Estate Property Finder App",
    "Music Player Mobile Application",
    "News Reader Mobile Application",
    "Chat and Messaging Mobile App",
    "Restaurant Table Booking App",
    "E-Commerce Shopping Mobile App",
    "Weather Forecast Mobile App",
    "Job Portal Mobile Application",
    "Event Management Mobile App",
    "Digital Wallet Mobile App",
    "Medicine Delivery Mobile App",
    "Campus Navigation Mobile App",
    "Online Quiz Mobile Application"
  ],
  "AI & Machine Learning": [
    "Crop Yield Prediction using Machine Learning",
    "Sign Language Recognition using Deep Learning",
    "AI-Based Resume Screening System",
    "Deep Learning Image Classifier",
    "Intrusion Detection using Machine Learning",
    "Diabetes Prediction using ML",
    "Breast Cancer Detection using CNN",
    "Customer Churn Prediction Model",
    "Movie Recommendation System",
    "Handwriting Recognition System",
    "Traffic Congestion Prediction",
    "Fraud Detection using ML",
    "Speech Recognition System",
    "Object Detection in Images",
    "Sentiment Analysis Engine",
    "House Price Prediction Model",
    "Plant Leaf Disease Detection",
    "Employee Attrition Prediction",
    "Credit Risk Scoring Model",
    "Fake Review Detection System",
    "Autonomous Driving Lane Detection",
    "Age and Gender Detection System",
    "Music Recommendation Engine",
    "Anomaly Detection in Transactions",
    "Predictive Maintenance System"
  ],
  "Generative AI": [
    "AI Chatbot using Generative AI",
    "AI Image Generator Application",
    "AI Content Writing Assistant",
    "AI Code Generation Tool",
    "AI Resume Builder with LLM",
    "AI Customer Support Chatbot",
    "AI Story Writing Generator",
    "AI Email Reply Assistant",
    "AI Product Description Generator",
    "AI Language Translation Tool",
    "AI Question Answering System",
    "AI Meeting Summary Generator",
    "AI Blog Post Generator",
    "AI Interview Preparation Bot",
    "AI Legal Document Summarizer",
    "AI Medical Report Analyzer",
    "AI Study Notes Generator",
    "AI Social Media Caption Generator",
    "AI Presentation Slide Generator",
    "AI Voice Assistant Application",
    "AI Code Review Assistant",
    "AI SQL Query Generator",
    "AI Personalized Learning Tutor",
    "AI Marketing Copy Generator",
    "AI Research Paper Summarizer"
  ],
  "AWS": [
    "Cloud-Based File Storage System",
    "Serverless Image Processing App",
    "AWS Lambda Notification Service",
    "Cloud-Hosted E-Commerce Platform",
    "Auto-Scaling Web Application on AWS",
    "AWS S3 Document Management System",
    "Cloud-Based Backup and Recovery System",
    "AWS RDS Database Hosting Portal",
    "Serverless REST API on Lambda",
    "AWS CloudWatch Monitoring Dashboard",
    "Multi-Region Deployment Architecture",
    "AWS Cognito User Authentication System",
    "Cloud-Based Video Streaming Platform",
    "AWS EC2 Web Server Deployment",
    "Serverless Email Processing Pipeline",
    "AWS DynamoDB NoSQL Application",
    "Cloud-Based CI/CD Pipeline on AWS",
    "AWS API Gateway Microservices",
    "Elastic Load Balancer Web App",
    "AWS SNS Alert Notification System",
    "Cloud-Based Data Analytics Pipeline",
    "AWS SQS Message Queue System",
    "Serverless Chat Application on AWS",
    "AWS CloudFront CDN Website",
    "IoT Data Pipeline on AWS"
  ],
  "Cyber Security": [
    "Intrusion Detection System using ML",
    "Network Log Analysis for Threat Detection",
    "Phishing Website Detection with NLP",
    "Malware Classification using Deep Learning",
    "Password Strength Analyzer Tool",
    "SQL Injection Detection System",
    "Network Packet Sniffer Tool",
    "Two-Factor Authentication System",
    "Firewall Rule Management System",
    "Vulnerability Scanner Tool",
    "Encrypted File Storage System",
    "Brute Force Attack Detection System",
    "Web Application Security Scanner",
    "Digital Signature Verification System",
    "Secure Login with OTP System",
    "Ransomware Detection Tool",
    "Network Traffic Anomaly Detection",
    "Keylogger Detection Application",
    "Secure Chat with End-to-End Encryption",
    "Penetration Testing Report Generator",
    "DDoS Attack Detection System",
    "Steganography Hide Message Tool",
    "Hash Cracking Educational Tool",
    "Security Audit Log Analyzer",
    "Zero-Day Vulnerability Alert System"
  ],
  "Data Science": [
    "Diabetes Prediction using Machine Learning",
    "Data Science Dashboard for Sales Analytics",
    "Customer Segmentation using Data Science",
    "Stock Market Trend Analysis Dashboard",
    "COVID-19 Data Visualization Dashboard",
    "Customer Lifetime Value Prediction",
    "Retail Sales Forecasting Model",
    "Employee Performance Analytics Dashboard",
    "Social Media Trend Analysis",
    "Credit Card Spending Analysis",
    "Airline Delay Prediction Model",
    "Insurance Claim Analytics System",
    "E-Commerce Customer Behavior Analysis",
    "Healthcare Patient Data Analytics",
    "Energy Consumption Prediction Model",
    "Supply Chain Demand Forecasting",
    "Real Estate Market Analysis Dashboard",
    "Churn Analysis for Telecom Industry",
    "Fraud Analytics Dashboard",
    "Sports Performance Analytics System",
    "Education Student Performance Analytics",
    "Agriculture Yield Analytics Dashboard",
    "Weather Pattern Analysis System",
    "Public Transport Usage Analytics",
    "Movie Box Office Prediction Model"
  ],
  "SQL": [
    "Student Database Management System",
    "Hospital Patient Records Database",
    "E-Commerce Order Database System",
    "Employee HR Database Management",
    "Library Book Records Database",
    "Banking Transaction Database System",
    "Inventory Stock Database System",
    "School Result Database Management",
    "Hotel Reservation Database System",
    "Restaurant Order Database System",
    "Insurance Claims Database System",
    "University Course Database System",
    "Vehicle Registration Database System",
    "Movie Ticket Booking Database",
    "Online Shopping Cart Database",
    "Payroll Processing Database System",
    "Customer CRM Database System",
    "Flight Booking Database System",
    "Pharmacy Stock Database System",
    "Real Estate Property Database",
    "Sports League Statistics Database",
    "Election Voting Database System",
    "Warehouse Logistics Database",
    "Subscription Billing Database System",
    "Network Log Storage Database"
  ],
  "MongoDB": [
    "NoSQL Based Student Feedback System",
    "Social Media Posts Storage System",
    "Blog Content Management with MongoDB",
    "Real-Time Chat Message Database",
    "Product Catalog NoSQL Application",
    "IoT Sensor Data Storage System",
    "Event Logging NoSQL Application",
    "User Activity Tracking Database",
    "E-Commerce Cart MongoDB Backend",
    "Notification History Storage System",
    "Survey Response Collection System",
    "Game Leaderboard Database System",
    "Location Tracking Data Store",
    "Content Recommendation Database",
    "Analytics Event Storage System",
    "Multi-Tenant SaaS Database",
    "Document Version Control System",
    "Review and Rating Storage System",
    "Job Listing NoSQL Platform",
    "News Article Publishing Database",
    "Chatbot Conversation History Store",
    "Digital Asset Metadata Database",
    "API Request Log Storage System",
    "Customer Support Ticket Database",
    "Mobile App User Profile Database"
  ],
  "MySQL": [
    "Gym Management System",
    "Hospital Management System with MySQL",
    "Online Examination System Database",
    "College Management System",
    "Restaurant Billing System",
    "Library Management with MySQL",
    "Employee Attendance System",
    "Online Shopping Store Database",
    "Student Registration System",
    "Hotel Management Database System",
    "Blood Bank Management System",
    "School Fee Management System",
    "Inventory Management with MySQL",
    "Online Bus Booking System",
    "Clinic Appointment System",
    "Payroll Management Database",
    "Online Food Ordering Database",
    "Car Rental Management System",
    "Alumni Record Management System",
    "Complaint Management Database",
    "Online Quiz System Database",
    "Travel Agency Booking Database",
    "Pharmacy Inventory System",
    "Sports Event Registration Database",
    "Online Voting System Database"
  ],
  "Basic DevOps": [
    "Automated Server Deployment Pipeline",
    "Docker Containerized Web Application",
    "CI/CD Pipeline with GitHub Actions",
    "Kubernetes Microservices Deployment",
    "Infrastructure as Code with Terraform",
    "Automated Backup and Restore System",
    "Log Monitoring and Alerting Pipeline",
    "Blue-Green Deployment Setup",
    "Docker Compose Multi-Service App",
    "Automated Testing in CI Pipeline",
    "Nginx Reverse Proxy Configuration",
    "SSL Certificate Automation System",
    "Server Health Monitoring Dashboard",
    "Automated Database Migration Pipeline",
    "Container Registry Management System",
    "Environment Configuration Management",
    "Rolling Update Deployment System",
    "Infrastructure Monitoring with Prometheus",
    "Automated Rollback Deployment System",
    "Multi-Stage Docker Build Pipeline",
    "Git Branch Based Deployment System",
    "Server Provisioning Automation",
    "Load Balancer Setup and Configuration",
    "Secrets Management in CI/CD",
    "Zero-Downtime Deployment Pipeline"
  ]
};
